import React, { useEffect, useState } from "react";
import { Alert } from "../../components/erp/Alert.jsx";
import { DataTable } from "../../components/erp/DataTable.jsx";
import { Field } from "../../components/erp/Field.jsx";
import { FilterBar } from "../../components/erp/FilterBar.jsx";
import { PageHeader } from "../../components/erp/PageHeader.jsx";
import { api } from "../../lib/api.js";

export function AuditLogListPage() { const [draft, setDraft] = useState({ fromDate: "", untilDate: "", entityType: "", page: 1, pageSize: 50 }); const [filters, setFilters] = useState(draft); const [data, setData] = useState({ items: [], totalCount: 0, page: 1, pageSize: 50, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value !== "" && params.set(key, value)); setLoading(true); api.get(`/api/audit-logs/?${params}`).then(setData).catch((e) => setError(e.message || "Không thể tải audit log.")).finally(() => setLoading(false)); }, [filters]); const columns = [{ key: "performedAt", label: "Thời gian", render: (row) => new Date(row.performedAt).toLocaleString("vi-VN") }, { key: "performedByUsername", label: "Người thực hiện" }, { key: "entityType", label: "Đối tượng" }, { key: "action", label: "Hành động" }, { key: "entityId", label: "Entity ID" }]; return <div className="erp-feature-page"><PageHeader title="Audit log" description="Theo dõi thay đổi dữ liệu và người thực hiện." />{error && <Alert variant="error" title="Không thể tải audit log.">{error}</Alert>}<FilterBar loading={loading} onSubmit={(e) => { e.preventDefault(); setFilters({ ...draft, page: 1 }); }} onReset={() => { const reset = { fromDate: "", untilDate: "", entityType: "", page: 1, pageSize: 50 }; setDraft(reset); setFilters(reset); }}><Field label="Từ ngày"><input className="erp-control" type="date" value={draft.fromDate} onChange={(e) => setDraft({ ...draft, fromDate: e.target.value })} /></Field><Field label="Đến ngày"><input className="erp-control" type="date" value={draft.untilDate} onChange={(e) => setDraft({ ...draft, untilDate: e.target.value })} /></Field><Field label="Loại đối tượng"><input className="erp-control" value={draft.entityType} onChange={(e) => setDraft({ ...draft, entityType: e.target.value })} /></Field></FilterBar><DataTable columns={columns} rows={data.items} loading={loading} error={error} emptyMessage="Chưa có audit log." rowKey="id" /></div>; }
