import React, { useEffect, useMemo, useState } from "react";
import { Alert } from "../../components/erp/Alert.jsx";
import { DataTable } from "../../components/erp/DataTable.jsx";
import { Field } from "../../components/erp/Field.jsx";
import { FormSection } from "../../components/erp/FormSection.jsx";
import { PageHeader } from "../../components/erp/PageHeader.jsx";
import { api } from "../../lib/api.js";

export function UserAccountPage() {
  const [accounts, setAccounts] = useState([]); const [employees, setEmployees] = useState([]); const [form, setForm] = useState({ username: "", password: "", role: "Worker", employeeId: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => Promise.all([api.get("/api/admin/user-accounts"), api.get("/api/employees")]).then(([a, e]) => { setAccounts(a); setEmployees(e); }).catch((requestError) => setError(requestError.message || "Không thể tải tài khoản.")); useEffect(load, []);
  const assignedIds = useMemo(() => new Set(accounts.filter((x) => x.employeeId).map((x) => String(x.employeeId))), [accounts]);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { await api.post("/api/admin/user-accounts", { ...form, username: form.username.trim(), employeeId: form.employeeId || null }); setForm({ username: "", password: "", role: "Worker", employeeId: "" }); await load(); } catch (requestError) { setError(requestError.message || "Không thể tạo tài khoản."); } finally { setSaving(false); } }
  const columns = [{ key: "username", label: "Tên đăng nhập" }, { key: "role", label: "Vai trò" }, { key: "employeeName", label: "Nhân viên", render: (row) => row.employeeCode ? `${row.employeeCode} — ${row.employeeName}` : "Không gắn nhân viên" }];
  return <div className="erp-feature-page"><PageHeader title="Tài khoản" description="Quản lý tài khoản và vai trò truy cập." />{error && <Alert variant="error" title="Không thể hoàn tất thao tác.">{error}</Alert>}<FormSection title="Tạo tài khoản"><Field label="Tên đăng nhập" required><input className="erp-control" required value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></Field><Field label="Mật khẩu" required><input className="erp-control" required minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></Field><Field label="Vai trò"><select className="erp-control" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="Worker">Công nhân</option><option value="Manager">Quản lý</option><option value="Admin">Admin</option></select></Field><Field label="Gắn nhân viên"><select className="erp-control" required={form.role === "Worker"} value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })}><option value="">Không gắn</option>{employees.filter((item) => item.isActive && !assignedIds.has(String(item.id))).map((item) => <option key={item.id} value={item.id}>{item.employeeCode} — {item.fullName}</option>)}</select></Field><div className="erp-field-wide erp-form-actions"><button className="erp-button erp-button-primary" type="submit" form="account-create" disabled={saving}>{saving ? "Đang lưu..." : "Tạo tài khoản"}</button></div></FormSection><form id="account-create" onSubmit={submit} hidden /><DataTable columns={columns} rows={accounts} loading={false} error={error} emptyMessage="Chưa có tài khoản." rowKey="id" /></div>;
}
