name: ci

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-domain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Restore domain tests
        run: dotnet restore tests/German.Domain.Tests/German.Domain.Tests.csproj
      - name: Test domain
        run: dotnet test tests/German.Domain.Tests/German.Domain.Tests.csproj --no-restore --configuration Release
